// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AdaSVRG
List AdaSVRG();
RcppExport SEXP AdaOpt_AdaSVRG() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(AdaSVRG());
    return __result;
END_RCPP
}
