// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AdaOpt
List AdaOpt(std::string method, NumericMatrix X, NumericVector Y, double lambda, uint epochs, bool verbose);
RcppExport SEXP AdaOpt_AdaOpt(SEXP methodSEXP, SEXP XSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP epochsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< uint >::type epochs(epochsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(AdaOpt(method, X, Y, lambda, epochs, verbose));
    return __result;
END_RCPP
}
// AdaSGDTest
List AdaSGDTest(NumericMatrix X, NumericVector Y, NumericVector W);
RcppExport SEXP AdaOpt_AdaSGDTest(SEXP XSEXP, SEXP YSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    __result = Rcpp::wrap(AdaSGDTest(X, Y, W));
    return __result;
END_RCPP
}
