# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AdaSGDOpt <- function(X, Y, lambda = 0.0001, epoch = 30L, num_rounds = 10L) {
    .Call('AdaOpt_AdaSGDOpt', PACKAGE = 'AdaOpt', X, Y, lambda, epoch, num_rounds)
}

AdaSDCAOpt <- function(X, Y, lambda = 0.0001, epoch = 30L, num_rounds = 10L) {
    .Call('AdaOpt_AdaSDCAOpt', PACKAGE = 'AdaOpt', X, Y, lambda, epoch, num_rounds)
}

AdaSDCAPlusOpt <- function(X, Y, lambda = 0.0001, epoch = 30L, num_rounds = 10L) {
    .Call('AdaOpt_AdaSDCAPlusOpt', PACKAGE = 'AdaOpt', X, Y, lambda, epoch, num_rounds)
}

NonUnifSGDOpt <- function(X, Y, lambda = 0.0001, epoch = 30L, num_rounds = 10L) {
    .Call('AdaOpt_NonUnifSGDOpt', PACKAGE = 'AdaOpt', X, Y, lambda, epoch, num_rounds)
}

NonUnifSDCAOpt <- function(X, Y, lambda = 0.0001, epoch = 30L, num_rounds = 10L) {
    .Call('AdaOpt_NonUnifSDCAOpt', PACKAGE = 'AdaOpt', X, Y, lambda, epoch, num_rounds)
}

AdaGradOpt <- function(X, Y, lambda = 0.0001, epoch = 30L, num_rounds = 10L) {
    .Call('AdaOpt_AdaGradOpt', PACKAGE = 'AdaOpt', X, Y, lambda, epoch, num_rounds)
}

AdaSVRGOpt <- function(X, Y, lambda = 0.0001, epoch = 30L, num_rounds = 10L) {
    .Call('AdaOpt_AdaSVRGOpt', PACKAGE = 'AdaOpt', X, Y, lambda, epoch, num_rounds)
}

