# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AdaOpt <- function(method, X, Y, lambda = 0.0001, epochs = 30L) {
    .Call('AdaOpt_AdaOpt', PACKAGE = 'AdaOpt', method, X, Y, lambda, epochs)
}

AdaSGDTest <- function(X, Y, W) {
    .Call('AdaOpt_AdaSGDTest', PACKAGE = 'AdaOpt', X, Y, W)
}

